version: "3"
services:
  victim:
    build: ./victim
    ports:
      - "8080:8080"

  attacker-client:
    build: ./attacker-client

  attacker-ldap:
    build: ./attacker-ldap
    ports:
      - "1389:1389"
      - "389:389"